Conference Assignment System: MaxFlow Class Reference
MaxFlow Class Reference
Implements the Edmonds-Karp algorithm for maximum flow.
#include <MaxFlow.h>
Public Member Functions
int edmondsKarp (Graph &graph, int source, int sink)
Computes the maximum flow from source to sink using Edmonds-Karp.
Private Member Functions
bool bfs (Graph &graph, int source, int sink, std::vector< int > &parent, std::vector< int > &parentEdge)
Finds an augmenting path from source to sink using BFS.
Detailed Description
Implements the Edmonds-Karp algorithm for maximum flow.
Uses BFS to find augmenting paths in the residual graph and updates the flow until no more augmenting paths exist. This is a BFS-based variant of the Ford-Fulkerson method.
Definition at line 23 of file MaxFlow.h.
Member Function Documentation
bfs()
bool MaxFlow::bfs (Graph & graph, int source, int sink, std::vector< int > & parent, std::vector< int > & parentEdge) private
Finds an augmenting path from source to sink using BFS.
Traverses the residual graph looking for a path with available capacity. Populates parent and parentEdge vectors for path reconstruction.
Parameters
graph The flow network (residual graph).
source The source node index.
sink The sink node index.
parent Output vector: parent[v] = predecessor of v in the BFS tree.
parentEdge Output vector: parentEdge[v] = index of the edge used to reach v.
Returns
true if an augmenting path was found, false otherwise.
\par Complexity: O(V + E)
Definition at line 12 of file MaxFlow.cpp.
References Edge::capacity, Edge::flow, Graph::getAdj(), Graph::size(), and Edge::to.
Referenced by edmondsKarp().
edmondsKarp()
int MaxFlow::edmondsKarp (Graph & graph, int source, int sink)
Computes the maximum flow from source to sink using Edmonds-Karp.
Repeatedly finds augmenting paths via BFS and pushes the maximum possible flow along each path until no more paths exist.
Parameters
graph The flow network to compute max flow on.
source The source node index.
sink The sink node index.
Returns
The value of the maximum flow.
\par Complexity: O(V * E^2)
Definition at line 51 of file MaxFlow.cpp.
References bfs(), Edge::capacity, Edge::flow, Graph::getAdj(), and Edge::rev.
Referenced by AssignmentEngine::solveBaseAssignment().
The documentation for this class was generated from the following files:
MaxFlow.h
MaxFlow.cpp