Conference Assignment System: RiskAnalyzer Class Reference
RiskAnalyzer Class Reference
Analyzes the impact of removing reviewers from the assignment problem.
#include <RiskAnalyzer.h>
Public Member Functions
std::vector< int > findCriticalReviewersForK1 () const
Finds all critical reviewers for the case K = 1.
RiskAnalyzer (const std::vector< Submission > &submissions, const std::vector< Reviewer > &reviewers, const Config &config)
Constructs the risk analyzer with the problem data.
Private Attributes
Config config
Copy of the configuration.
std::vector< Reviewer > reviewers
Copy of the reviewers list.
std::vector< Submission > submissions
Copy of the submissions list.
Detailed Description
Analyzes the impact of removing reviewers from the assignment problem.
For Risk Analysis with K = 1, each reviewer is removed one at a time and the assignment problem is solved again. If the assignment becomes invalid (i.e., max flow < required flow), that reviewer is critical.
Definition at line 26 of file RiskAnalyzer.h.
Constructor & Destructor Documentation
RiskAnalyzer()
RiskAnalyzer::RiskAnalyzer (const std::vector< Submission > & submissions, const std::vector< Reviewer > & reviewers, const Config & config)
Constructs the risk analyzer with the problem data.
Parameters
submissions The list of submissions.
reviewers The list of reviewers.
config The configuration parameters.
Definition at line 9 of file RiskAnalyzer.cpp.
Member Function Documentation
findCriticalReviewersForK1()
std::vector< int > RiskAnalyzer::findCriticalReviewersForK1 () const
Finds all critical reviewers for the case K = 1.
A reviewer is considered critical if removing that reviewer makes it impossible to obtain a valid complete assignment (i.e., the max flow drops below the required flow).
Returns
A vector of reviewer IDs that are critical.
\par Complexity: O(R * V * E^2) where R = number of reviewers, V = vertices in the flow network, E = edges.
Definition at line 16 of file RiskAnalyzer.cpp.
References config, AssignmentEngine::getRequiredFlow(), reviewers, AssignmentEngine::solveBaseAssignment(), and submissions.
Referenced by runBatchMode(), and Menu::runRiskAnalysis().
Member Data Documentation
config
Config RiskAnalyzer::config private
Copy of the configuration.
Definition at line 30 of file RiskAnalyzer.h.
Referenced by findCriticalReviewersForK1().
reviewers
std::vector<Reviewer> RiskAnalyzer::reviewers private
Copy of the reviewers list.
Definition at line 29 of file RiskAnalyzer.h.
Referenced by findCriticalReviewersForK1().
submissions
std::vector<Submission> RiskAnalyzer::submissions private
Copy of the submissions list.
Definition at line 28 of file RiskAnalyzer.h.
Referenced by findCriticalReviewersForK1().
The documentation for this class was generated from the following files:
RiskAnalyzer.h
RiskAnalyzer.cpp