Conference Assignment System: CsvParser Class Reference
CsvParser Class Reference
Handles the extraction of data from a formatted CSV file.
#include <CsvParser.h>
Public Member Functions
CsvParser (std::string filename)
Constructor for the CsvParser.
const Config & getConfig () const
Provides access to the global configuration parameters.
const std::vector< Reviewer > & getReviewers () const
Provides access to the list of parsed reviewers.
const std::vector< Submission > & getSubmissions () const
Provides access to the list of parsed submissions.
bool parse ()
Orchestrates the parsing process of the CSV file.
Private Member Functions
std::string removeComments (const std::string &line)
Removes comments starting with '#' from a line.
std::vector< std::string > splitCsvLine (const std::string &line)
Splits a CSV line into tokens based on the ';' delimiter.
std::string trim (const std::string &str)
Removes leading and trailing whitespace from a string.
Private Attributes
Config config
Configuration parameters parsed from the file.
std::string filename
Path to the input CSV file.
std::unordered_set< int > reviewerIds
Helper set to ensure reviewer IDs are unique.
std::vector< Reviewer > reviewers
Collection of parsed reviewers.
std::unordered_set< int > submissionIds
Helper set to ensure submission IDs are unique.
std::vector< Submission > submissions
Collection of parsed submissions.
Detailed Description
Handles the extraction of data from a formatted CSV file.
The class processes four main sections: Submissions, Reviewers, Parameters, and Control. It ensures data integrity by checking for duplicate IDs and ignoring comments or empty lines.
Definition at line 24 of file CsvParser.h.
Constructor & Destructor Documentation
CsvParser()
CsvParser::CsvParser (std::string filename) explicit
Constructor for the CsvParser.
Parameters
filename The path to the CSV file to be processed.
Definition at line 12 of file CsvParser.cpp.
Member Function Documentation
getConfig()
const Config & CsvParser::getConfig () const inline
Provides access to the global configuration parameters.
Returns
A constant reference to the Config object.
Definition at line 87 of file CsvParser.h.
References config.
Referenced by Menu::generateAssignment(), runBatchMode(), Menu::runRiskAnalysis(), and Menu::showParameters().
getReviewers()
const std::vector< Reviewer > & CsvParser::getReviewers () const inline
Provides access to the list of parsed reviewers.
Returns
A constant reference to a vector of Reviewer objects.
Definition at line 81 of file CsvParser.h.
References reviewers.
Referenced by Menu::generateAssignment(), Menu::listReviewers(), Menu::loadFile(), runBatchMode(), and Menu::runRiskAnalysis().
getSubmissions()
const std::vector< Submission > & CsvParser::getSubmissions () const inline
Provides access to the list of parsed submissions.
Returns
A constant reference to a vector of Submission objects.
Definition at line 75 of file CsvParser.h.
References submissions.
Referenced by Menu::generateAssignment(), Menu::listSubmissions(), Menu::loadFile(), runBatchMode(), and Menu::runRiskAnalysis().
parse()
bool CsvParser::parse ()
Orchestrates the parsing process of the CSV file.
Main parsing loop using a State Machine approach.
Reads the file line by line, identifies sections, and populates the corresponding data structures (Submissions, Reviewers, Config).
Returns
true if the file was parsed successfully without critical errors, false if the file could not be opened or has severe formatting issues.
The method identifies headers (e.g., Submissions) to switch states and determines how to process subsequent lines based on the current state. Includes error handling for duplicated IDs, malformed integers, and validation of mandatory parameters.
Returns
true if the file was parsed successfully, false otherwise. \par Complexity: O(N) where N is the number of lines in the file.
Internal states to track which section of the CSV is being read.
Definition at line 73 of file CsvParser.cpp.
References config, filename, removeComments(), reviewerIds, reviewers, Config::setGenerateAssignments(), Config::setMaxReviewsPerReviewer(), Config::setMinReviewsPerSubmission(), Config::setOutputFileName(), Config::setRiskAnalysis(), splitCsvLine(), submissionIds, submissions, and trim().
Referenced by Menu::loadFile(), and runBatchMode().
removeComments()
std::string CsvParser::removeComments (const std::string & line) private
Removes comments starting with '#' from a line.
Strips comments from the input line.
Parameters
line The raw line to be cleaned.
Returns
The line content before the '#' character.
This allows the parser to ignore everything after the '#' character within data lines.
Definition at line 30 of file CsvParser.cpp.
Referenced by parse().
splitCsvLine()
std::vector< std::string > CsvParser::splitCsvLine (const std::string & line) private
Splits a CSV line into tokens based on the ';' delimiter.
Custom CSV splitter that handles quoted fields.
Parameters
line The raw line from the CSV file.
Returns
A vector of strings containing the individual columns.
Iterates through the line character by character to ensure commas inside quotes don't break the tokenization.
Definition at line 43 of file CsvParser.cpp.
References trim().
Referenced by parse().
trim()
std::string CsvParser::trim (const std::string & str) private
Removes leading and trailing whitespace from a string.
Cleans strings by removing whitespace and quotes.
Parameters
str The string to be trimmed.
Returns
A new string without surrounding whitespace.
Useful for handling CSV fields that might have inconsistent spacing.
Definition at line 18 of file CsvParser.cpp.
Referenced by parse(), and splitCsvLine().
Member Data Documentation
config
Config CsvParser::config private
Configuration parameters parsed from the file.
Definition at line 29 of file CsvParser.h.
Referenced by getConfig(), and parse().
filename
std::string CsvParser::filename private
Path to the input CSV file.
Definition at line 26 of file CsvParser.h.
Referenced by parse().
reviewerIds
std::unordered_set<int> CsvParser::reviewerIds private
Helper set to ensure reviewer IDs are unique.
Definition at line 32 of file CsvParser.h.
Referenced by parse().
reviewers
std::vector<Reviewer> CsvParser::reviewers private
Collection of parsed reviewers.
Definition at line 28 of file CsvParser.h.
Referenced by getReviewers(), and parse().
submissionIds
std::unordered_set<int> CsvParser::submissionIds private
Helper set to ensure submission IDs are unique.
Definition at line 31 of file CsvParser.h.
Referenced by parse().
submissions
std::vector<Submission> CsvParser::submissions private
Collection of parsed submissions.
Definition at line 27 of file CsvParser.h.
Referenced by getSubmissions(), and parse().
The documentation for this class was generated from the following files:
CsvParser.h
CsvParser.cpp