Conference Assignment System: AssignmentEngine Class Reference
AssignmentEngine Class Reference
Builds and solves the reviewer assignment problem using max-flow.
#include <AssignmentEngine.h>
Public Member Functions
AssignmentEngine (const std::vector< Submission > &submissions, const std::vector< Reviewer > &reviewers, const Config &config)
Constructs the assignment engine.
const std::vector< Assignment > & getAssignments () const
Returns the computed assignments.
int getLastComputedFlow () const
Returns the computed flow.
const std::vector< MissingReview > & getMissingReviews () const
Returns missing reviews for submissions.
int getRequiredFlow () const
Returns the required total flow.
bool hasValidAssignment () const
Checks if a valid assignment exists.
int solveBaseAssignment ()
Solves the assignment problem using max-flow.
Private Member Functions
void buildBaseGraph ()
Builds the flow network based on the current assignment mode.
void calculateMissingReviews ()
Calculates missing reviews for each submission.
void extractAssignments ()
Extracts assignments from the computed flow.
int getMatchTopic (const Reviewer &reviewer, const Submission &submission) const
Determines the matched topic between a reviewer and submission.
int getReviewerIndexFromNode (int node) const
int getReviewerNode (int reviewerIndex) const
int getSubmissionIndexFromNode (int node) const
int getSubmissionNode (int submissionIndex) const
void initializeGraph ()
Initializes the graph structure.
bool isCompatible (const Reviewer &reviewer, const Submission &submission) const
Checks if a reviewer is compatible with a submission.
Private Attributes
std::vector< Assignment > assignments
Config config
Graph graph
int lastComputedFlow
MaxFlow maxFlow
std::vector< MissingReview > missingReviews
int reviewerOffset
std::vector< Reviewer > reviewers
int sink
int source
int submissionOffset
std::vector< Submission > submissions
int totalNodes
Detailed Description
Builds and solves the reviewer assignment problem using max-flow.
Constructs a flow network where reviewers are matched to submissions based on domain expertise, and computes a valid assignment using the Edmonds-Karp algorithm. Supports different assignment modes:
Mode 0/1: Primary domains only.
Mode 2: Primary + Secondary submission domains, Primary reviewer expertise.
Mode 3: All primary and secondary domains of both.
\par Complexity: O(V * E^2) for the max-flow computation.
Definition at line 42 of file AssignmentEngine.h.
Constructor & Destructor Documentation
AssignmentEngine()
AssignmentEngine::AssignmentEngine (const std::vector< Submission > & submissions, const std::vector< Reviewer > & reviewers, const Config & config)
Constructs the assignment engine.
Definition at line 3 of file AssignmentEngine.cpp.
References graph, sink, submissionOffset, submissions, and totalNodes.
Member Function Documentation
buildBaseGraph()
void AssignmentEngine::buildBaseGraph () private
Builds the flow network based on the current assignment mode.
\par Complexity: O(R * S)
Definition at line 104 of file AssignmentEngine.cpp.
References Graph::addEdge(), config, Config::getMaxReviewsPerReviewer(), Config::getMinReviewsPerSubmission(), getReviewerNode(), getSubmissionNode(), graph, isCompatible(), reviewers, sink, source, and submissions.
Referenced by solveBaseAssignment().
calculateMissingReviews()
void AssignmentEngine::calculateMissingReviews () private
Calculates missing reviews for each submission.
\par Complexity: O(S)
Definition at line 148 of file AssignmentEngine.cpp.
References config, Graph::getAdj(), Config::getMinReviewsPerSubmission(), getSubmissionNode(), graph, MissingReview::missingReviews, missingReviews, sink, MissingReview::submissionId, submissions, and MissingReview::topic.
Referenced by solveBaseAssignment().
extractAssignments()
void AssignmentEngine::extractAssignments () private
Extracts assignments from the computed flow.
\par Complexity: O(R * S)
Definition at line 127 of file AssignmentEngine.cpp.
References assignments, Graph::getAdj(), getMatchTopic(), getReviewerNode(), getSubmissionIndexFromNode(), graph, Assignment::reviewerId, reviewers, sink, Assignment::submissionId, submissionOffset, submissions, and Assignment::topic.
Referenced by solveBaseAssignment().
getAssignments()
const std::vector< Assignment > & AssignmentEngine::getAssignments () const
Returns the computed assignments.
Definition at line 197 of file AssignmentEngine.cpp.
References assignments.
Referenced by Menu::generateAssignment(), and runBatchMode().
getLastComputedFlow()
int AssignmentEngine::getLastComputedFlow () const
Returns the computed flow.
Definition at line 189 of file AssignmentEngine.cpp.
References lastComputedFlow.
getMatchTopic()
int AssignmentEngine::getMatchTopic (const Reviewer & reviewer, const Submission & submission) const private
Determines the matched topic between a reviewer and submission.
\par Complexity: O(1)
Definition at line 57 of file AssignmentEngine.cpp.
References config, Config::getGenerateAssignments(), Reviewer::getPrimaryExpertise(), Submission::getPrimaryTopic(), Reviewer::getSecondaryExpertise(), and Submission::getSecondaryTopic().
Referenced by extractAssignments().
getMissingReviews()
const std::vector< MissingReview > & AssignmentEngine::getMissingReviews () const
Returns missing reviews for submissions.
Definition at line 201 of file AssignmentEngine.cpp.
References missingReviews.
Referenced by Menu::generateAssignment(), and runBatchMode().
getRequiredFlow()
int AssignmentEngine::getRequiredFlow () const
Returns the required total flow.
Definition at line 185 of file AssignmentEngine.cpp.
References config, Config::getMinReviewsPerSubmission(), and submissions.
Referenced by RiskAnalyzer::findCriticalReviewersForK1(), Menu::generateAssignment(), hasValidAssignment(), and runBatchMode().
getReviewerIndexFromNode()
int AssignmentEngine::getReviewerIndexFromNode (int node) const private
Definition at line 96 of file AssignmentEngine.cpp.
References reviewerOffset.
getReviewerNode()
int AssignmentEngine::getReviewerNode (int reviewerIndex) const private
Definition at line 88 of file AssignmentEngine.cpp.
References reviewerOffset.
Referenced by buildBaseGraph(), and extractAssignments().
getSubmissionIndexFromNode()
int AssignmentEngine::getSubmissionIndexFromNode (int node) const private
Definition at line 100 of file AssignmentEngine.cpp.
References submissionOffset.
Referenced by extractAssignments().
getSubmissionNode()
int AssignmentEngine::getSubmissionNode (int submissionIndex) const private
Definition at line 92 of file AssignmentEngine.cpp.
References submissionOffset.
Referenced by buildBaseGraph(), and calculateMissingReviews().
hasValidAssignment()
bool AssignmentEngine::hasValidAssignment () const
Checks if a valid assignment exists.
Definition at line 193 of file AssignmentEngine.cpp.
References getRequiredFlow(), and lastComputedFlow.
Referenced by Menu::generateAssignment(), and runBatchMode().
initializeGraph()
void AssignmentEngine::initializeGraph () private
Initializes the graph structure.
\par Complexity: O(V)
Definition at line 22 of file AssignmentEngine.cpp.
References assignments, graph, lastComputedFlow, missingReviews, and totalNodes.
Referenced by solveBaseAssignment().
isCompatible()
bool AssignmentEngine::isCompatible (const Reviewer & reviewer, const Submission & submission) const private
Checks if a reviewer is compatible with a submission.
Uses the GenerateAssignments mode from the config to determine which domains to consider for compatibility.
\par Complexity: O(1)
Definition at line 29 of file AssignmentEngine.cpp.
References config, Config::getGenerateAssignments(), Reviewer::getPrimaryExpertise(), Submission::getPrimaryTopic(), Reviewer::getSecondaryExpertise(), and Submission::getSecondaryTopic().
Referenced by buildBaseGraph().
solveBaseAssignment()
int AssignmentEngine::solveBaseAssignment ()
Solves the assignment problem using max-flow.
\par Complexity: O(V * E^2)
Definition at line 176 of file AssignmentEngine.cpp.
References buildBaseGraph(), calculateMissingReviews(), MaxFlow::edmondsKarp(), extractAssignments(), graph, initializeGraph(), lastComputedFlow, maxFlow, sink, and source.
Referenced by RiskAnalyzer::findCriticalReviewersForK1(), Menu::generateAssignment(), and runBatchMode().
Member Data Documentation
assignments
std::vector<Assignment> AssignmentEngine::assignments private
Definition at line 58 of file AssignmentEngine.h.
Referenced by extractAssignments(), getAssignments(), and initializeGraph().
config
Config AssignmentEngine::config private
Definition at line 46 of file AssignmentEngine.h.
Referenced by buildBaseGraph(), calculateMissingReviews(), getMatchTopic(), getRequiredFlow(), and isCompatible().
graph
Graph AssignmentEngine::graph private
Definition at line 48 of file AssignmentEngine.h.
Referenced by AssignmentEngine(), buildBaseGraph(), calculateMissingReviews(), extractAssignments(), initializeGraph(), and solveBaseAssignment().
lastComputedFlow
int AssignmentEngine::lastComputedFlow private
Definition at line 56 of file AssignmentEngine.h.
Referenced by getLastComputedFlow(), hasValidAssignment(), initializeGraph(), and solveBaseAssignment().
maxFlow
MaxFlow AssignmentEngine::maxFlow private
Definition at line 49 of file AssignmentEngine.h.
Referenced by solveBaseAssignment().
missingReviews
std::vector<MissingReview> AssignmentEngine::missingReviews private
Definition at line 59 of file AssignmentEngine.h.
Referenced by calculateMissingReviews(), getMissingReviews(), and initializeGraph().
reviewerOffset
int AssignmentEngine::reviewerOffset private
Definition at line 53 of file AssignmentEngine.h.
Referenced by getReviewerIndexFromNode(), and getReviewerNode().
reviewers
std::vector<Reviewer> AssignmentEngine::reviewers private
Definition at line 45 of file AssignmentEngine.h.
Referenced by buildBaseGraph(), and extractAssignments().
sink
int AssignmentEngine::sink private
Definition at line 52 of file AssignmentEngine.h.
Referenced by AssignmentEngine(), buildBaseGraph(), calculateMissingReviews(), extractAssignments(), and solveBaseAssignment().
source
int AssignmentEngine::source private
Definition at line 51 of file AssignmentEngine.h.
Referenced by buildBaseGraph(), and solveBaseAssignment().
submissionOffset
int AssignmentEngine::submissionOffset private
Definition at line 54 of file AssignmentEngine.h.
Referenced by AssignmentEngine(), extractAssignments(), getSubmissionIndexFromNode(), and getSubmissionNode().
submissions
std::vector<Submission> AssignmentEngine::submissions private
Definition at line 44 of file AssignmentEngine.h.
Referenced by AssignmentEngine(), buildBaseGraph(), calculateMissingReviews(), extractAssignments(), and getRequiredFlow().
totalNodes
int AssignmentEngine::totalNodes private
Definition at line 55 of file AssignmentEngine.h.
Referenced by AssignmentEngine(), and initializeGraph().
The documentation for this class was generated from the following files:
AssignmentEngine.h
AssignmentEngine.cpp