Conference Assignment System: Menu Class Reference
Menu Class Reference
Interactive CLI menu for the conference assignment system.
#include <Menu.h>
Public Member Functions
Menu ()
Constructor.
void run ()
Starts the interactive menu loop.
~Menu ()
Destructor.
Private Member Functions
void displayMenu () const
Displays the main menu options.
void generateAssignment ()
Generates the reviewer-submission assignment.
void listReviewers () const
Lists all parsed reviewers.
void listSubmissions () const
Lists all parsed submissions.
void loadFile ()
Loads and parses a CSV file.
void runRiskAnalysis ()
Runs risk analysis (K=1) and reports critical reviewers.
void showParameters () const
Displays the current configuration parameters.
Private Attributes
bool assignmentGenerated
bool dataLoaded
AssignmentEngine * engine
CsvParser * parser
Detailed Description
Interactive CLI menu for the conference assignment system.
Allows users to load CSV files, inspect parsed data, generate reviewer-submission assignments, and run risk analysis.
Definition at line 26 of file Menu.h.
Constructor & Destructor Documentation
Menu()
Menu::Menu ()
Constructor.
Definition at line 10 of file Menu.cpp.
~Menu()
Menu::~Menu ()
Destructor.
Cleans up allocated resources.
Definition at line 12 of file Menu.cpp.
References engine, and parser.
Member Function Documentation
displayMenu()
void Menu::displayMenu () const private
Displays the main menu options.
Definition at line 17 of file Menu.cpp.
Referenced by run().
generateAssignment()
void Menu::generateAssignment () private
Generates the reviewer-submission assignment.
Definition at line 114 of file Menu.cpp.
References assignmentGenerated, dataLoaded, engine, AssignmentEngine::getAssignments(), CsvParser::getConfig(), Config::getGenerateAssignments(), AssignmentEngine::getMissingReviews(), Config::getOutputFileName(), AssignmentEngine::getRequiredFlow(), CsvParser::getReviewers(), CsvParser::getSubmissions(), AssignmentEngine::hasValidAssignment(), parser, AssignmentEngine::solveBaseAssignment(), and OutputWriter::writeAssignments().
Referenced by run().
listReviewers()
void Menu::listReviewers () const private
Lists all parsed reviewers.
Definition at line 79 of file Menu.cpp.
References dataLoaded, CsvParser::getReviewers(), and parser.
Referenced by run().
listSubmissions()
void Menu::listSubmissions () const private
Lists all parsed submissions.
Definition at line 59 of file Menu.cpp.
References dataLoaded, CsvParser::getSubmissions(), and parser.
Referenced by run().
loadFile()
void Menu::loadFile () private
Loads and parses a CSV file.
Definition at line 32 of file Menu.cpp.
References assignmentGenerated, dataLoaded, engine, CsvParser::getReviewers(), CsvParser::getSubmissions(), CsvParser::parse(), and parser.
Referenced by run().
run()
void Menu::run ()
Starts the interactive menu loop.
Definition at line 209 of file Menu.cpp.
References displayMenu(), generateAssignment(), listReviewers(), listSubmissions(), loadFile(), runRiskAnalysis(), and showParameters().
Referenced by main().
runRiskAnalysis()
void Menu::runRiskAnalysis () private
Runs risk analysis (K=1) and reports critical reviewers.
Definition at line 168 of file Menu.cpp.
References dataLoaded, RiskAnalyzer::findCriticalReviewersForK1(), CsvParser::getConfig(), Config::getOutputFileName(), CsvParser::getReviewers(), Config::getRiskAnalysis(), CsvParser::getSubmissions(), parser, and OutputWriter::writeRiskAnalysis().
Referenced by run().
showParameters()
void Menu::showParameters () const private
Displays the current configuration parameters.
Definition at line 98 of file Menu.cpp.
References dataLoaded, CsvParser::getConfig(), Config::getGenerateAssignments(), Config::getMaxReviewsPerReviewer(), Config::getMinReviewsPerSubmission(), Config::getOutputFileName(), Config::getRiskAnalysis(), and parser.
Referenced by run().
Member Data Documentation
assignmentGenerated
bool Menu::assignmentGenerated private
Definition at line 31 of file Menu.h.
Referenced by generateAssignment(), and loadFile().
dataLoaded
bool Menu::dataLoaded private
Definition at line 30 of file Menu.h.
Referenced by generateAssignment(), listReviewers(), listSubmissions(), loadFile(), runRiskAnalysis(), and showParameters().
engine
AssignmentEngine* Menu::engine private
Definition at line 29 of file Menu.h.
Referenced by generateAssignment(), loadFile(), and ~Menu().
parser
CsvParser* Menu::parser private
Definition at line 28 of file Menu.h.
Referenced by generateAssignment(), listReviewers(), listSubmissions(), loadFile(), runRiskAnalysis(), showParameters(), and ~Menu().
The documentation for this class was generated from the following files:
Menu.h
Menu.cpp